/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "sa-east-1",
    "aws_cognito_identity_pool_id": "sa-east-1:d5b88b06-797a-4ea6-b3a8-8678d0f3bd6b",
    "aws_cognito_region": "sa-east-1",
    "aws_user_pools_id": "sa-east-1_Sd3HI7xHO",
    "aws_user_pools_web_client_id": "31qjtmrgs4990ipcc2m1tq5i54",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amplifys3bucket195100-dev",
    "aws_user_files_s3_bucket_region": "sa-east-1"
};


export default awsmobile;
