/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:2962d6bb-196f-4c74-be40-d44ed12674b6",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_WEs7ftU74",
    "aws_user_pools_web_client_id": "53vcbcj2uina5kh7bn0otgrv2k",
    "oauth": {},
    "aws_user_files_s3_bucket": "amplifys3bucket181300-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsconfig;
