/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:4933f85c-7e70-4d02-a038-7f0a6d68b33a",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_9kmH1TVVz",
    "aws_user_pools_web_client_id": "4qp29p7jsumvkc71ukqm8jpmio",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "amplifys3bucket125220-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsconfig;
